/**
 * Outbound transactional email via Resend.
 *
 * Credentials are env-only on purpose:
 *   - RESEND_API_KEY  — required
 *   - INVESTOR_FROM_EMAIL — required when distribution is on
 *   - INVESTOR_FROM_NAME  — optional, defaults to "LifeSupply"
 *
 * Returns null when the API key is missing so callers can fall back to a
 * stub release path. Per CLAUDE.md §15, distribution must also be gated on
 * the `investor.distribution` FeatureFlag — that check lives at the call
 * site.
 */

import { Resend } from "resend";

export type EmailEnvelope = {
  to: string[];
  /** Optional bcc list — used for investor distribution to keep recipients private. */
  bcc?: string[];
  subject: string;
  /** Plain-text body. HTML is generated by Resend from this when html is omitted. */
  text: string;
  /** Optional pre-rendered HTML. */
  html?: string;
};

export type EmailSendResult = {
  providerId: string;
  recipientCount: number;
};

export type ConfiguredEmail = {
  send: (envelope: EmailEnvelope) => Promise<EmailSendResult>;
  fromAddress: string;
};

export function getEmailClient(): ConfiguredEmail | null {
  const apiKey = process.env.RESEND_API_KEY;
  const fromEmail = process.env.INVESTOR_FROM_EMAIL;
  if (!apiKey || !fromEmail) return null;

  const fromName = process.env.INVESTOR_FROM_NAME ?? "LifeSupply";
  const resend = new Resend(apiKey);
  const fromAddress = `${fromName} <${fromEmail}>`;

  return {
    fromAddress,
    async send(envelope) {
      // Resend requires either `to` or `bcc` to be non-empty. We prefer
      // `bcc` for investor distribution so recipients can't see each
      // other; the `to` field then needs to be the from address itself.
      const useBcc = envelope.bcc && envelope.bcc.length > 0;
      const result = await resend.emails.send({
        from: fromAddress,
        to: useBcc ? [fromEmail] : envelope.to,
        bcc: useBcc ? envelope.bcc : undefined,
        subject: envelope.subject,
        text: envelope.text,
        html: envelope.html,
      });
      if (result.error) {
        throw new Error(`Resend rejected the message: ${result.error.message}`);
      }
      const id = result.data?.id ?? "unknown";
      const recipientCount =
        (envelope.to?.length ?? 0) + (envelope.bcc?.length ?? 0);
      return { providerId: id, recipientCount };
    },
  };
}
