/**
 * Title → icon key for the public content model. Content modules stay
 * plain data; a page passes `iconForTitle(item.title)` to a section
 * primitive, which resolves the key in `components/public-site/icons.ts`.
 * An unmapped title renders no icon rather than a wrong one. Keys are the
 * `ICONS` keys; a unit test checks every value here exists there.
 */
export const ICON_BY_TITLE: Record<string, string> = {
  // Metabolic Health
  "Starter supplies": "package",
  "Usage-driven consumables": "repeat",
  "Clinic procurement": "building",
  "Contracted workflow services": "workflow",
  Clinics: "stethoscope",
  Pharmacies: "pill",
  "Program participants": "users",
  Discuss: "mail",
  Configure: "settings",
  "Confirm availability": "badge",
  "Starter equipment": "package",
  Consumables: "repeat",
  "Occasional items": "boxes",
  // Clinic Solutions
  "Plan or renovate a clinic": "compass",
  "Equip a clinic": "clipboardCheck",
  "Equip it": "clipboardCheck",
  "Supply an existing clinic": "truck",
  "Keep it supplied": "truck",
  Planning: "compass",
  Design: "ruler",
  Construction: "building",
  "Project management": "clipboardList",
  "Understand the practice": "search",
  "Assess and plan": "compass",
  "Build and hand over": "badge",
  // Pharmacy Solutions
  "For the pharmacy": "pill",
  "For the patient": "heart",
  "For clinic pathways": "stethoscope",
  "For the group": "layout",
  // Partners
  "Suppliers and manufacturers": "boxes",
  "Acquisitions and strategic transactions": "handshake",
  "Program configuration": "settings",
  Pilots: "flask",
  "Design partnership": "ruler",
  "Pharmacist-selected configurations": "pill",
  "Non-drug only": "shield",
  "Fulfilment responsibilities stated per program": "clipboardCheck",
  Inquiry: "mail",
  Review: "search",
  "Commercial terms": "scroll",
  Listing: "cart",
  "Complementary categories or customers": "layout",
  "Integration rationale": "workflow",
  "Clinic and program adjacency": "stethoscope",
  Introduction: "mail",
  Confidentiality: "shield",
  Evaluation: "search",
  Terms: "scroll",
  // Investors
  "Operating foundation": "cart",
  "Clinic relationships": "stethoscope",
  "Metabolic-health supply services": "activity",
  "Regulated development and selective transactions": "flask",
  "Existing business improvement": "settings",
  "Clinic accounts": "building",
  "Metabolic supply and services": "activity",
  "Regulated development": "microscope",
  "Selective transactions": "handshake",
  "Growth strategy": "chart",
  "Advanced therapeutics": "flask",
  Documents: "file",
  "Shareholder services": "landmark",
  Disclosures: "shield",
  Pharmacy: "pill",
  "Specialty and compounding": "flask",
  "Peptide synthesis and research": "microscope",
  Manufacturing: "warehouse",
  Public: "globe",
  "Restricted, on request": "shield",
  Historical: "scroll",
  // Businesses
  "Who it serves": "users",
  Categories: "layout",
  "Service channels": "mail",
  "Its place on this site": "globe",
  // Metabolic Health (partner overview, September 2026)
  Start: "package",
  Continue: "repeat",
  Support: "handshake",
  "Patient supply pathways": "package",
  "Fulfilment & administration": "packageCheck",
  "Workflow & reporting": "chart",
  "Care programs": "activity",
  Contents: "boxes",
  Cadence: "repeat",
  Materials: "file",
  Presentation: "layout",
  Fulfilment: "truck",
  // Pharmacy Solutions
  "Non-drug supply programs": "pill",
  "Onboarding and refill support": "repeat",
  "Pharmacy-related operations": "building",
  "Regulated care infrastructure": "shield",
  "Pharmacy solutions": "pill",
  // Home and about
  Mission: "compass",
  Vision: "globe",
  Footprint: "pin",
  Milestones: "scroll",
  Partners: "handshake",
  Investors: "chart",
  // Operations narrative
  "Online ecommerce division": "cart",
  "Distribution & drop ship facility": "truck",
  "Flagship retail operations": "building",
  "Wholesale division": "warehouse",
  Pharmaceutical: "pill",
  // Brand registry names
  LifeSupply: "cart",
  "Wellmart Medical": "heart",
  "LifeSupply Clinics": "building",
  "Balkowitsch Worldwide": "globe",
  // Shop and contact
  "Geography and currency": "globe",
  "Support boundary": "shield",
  "Existing order?": "cart",
  "Clinic development": "compass",
  "Equipment quote": "clipboardCheck",
  "Ongoing procurement": "truck",
  "Metabolic-health program": "activity",
  "Pharmacy supply program": "pill",
  "Supplier or manufacturer": "boxes",
  Investor: "chart",
  "Acquisition or strategic transaction": "handshake",
  General: "mail",
  "Corporate office": "building",
  "Investor relations": "chart",
  "Online sales & product lines": "cart",
  "Mergers & acquisitions": "handshake",
  // Kit pathways, by id
  K01: "syringe",
  K02: "shield",
  K03: "boxes",
  K04: "briefcase",
  K05: "thermometer",
  K06: "activity",
  K07: "stethoscope",
  K08: "pill",
  // Item roles
  starter: "package",
  consumable: "repeat",
  occasional: "boxes",
};

export function iconForTitle(title: string): string | undefined {
  return ICON_BY_TITLE[title];
}
